### ISSUE TITLE
delete repo

### ISSUE THREAD

**Issue by looooo** [conda-forge/freecad.python-feedstock#3]
The source of this repo is now directly included in FreeCAD. Is it possible to delete this repository?
@conda-forge/core

**Comment by jjhelmus** [comment]
Would archiving the repository be reasonable?  That makes it read only so no one can submit PR or issues but the contents are still available to anyone looking for the historic record.

**Comment by looooo** [comment]
@jjhelmus yes, this should be ok.

**Comment by jjhelmus** [comment]
Sounds good, closing this issue and then archiving.
